### ISSUE TITLE
Calling FS when using relatedness and parentage

### ISSUE THREAD

**Issue by ThatLionLady** [RHagenson/relped#37]
PO and FS are both around 0.5. When parentage is provided, PO and FS can be called from relatedness based on the information provided. For example, Parent1 and Parent2 have Offspring1 and Offspring2. Between these four, there are 5 pairwise comparisons that will be around 0.5 (P1wO1, P2wO1, P1wO2, P2wO2, and O1wO2) but only two entries in the parentage accounting for the 4 comparisons between PO, therefore, the 5th comparison is between FS.

![image](https://user-images.githubusercontent.com/44615083/70661417-d5893f80-1c29-11ea-8ef5-7f69f72fc9b0.png)

**Comment by rhagenson** [comment]
In effect when the optional parentage file contains both parents of a pair of offspring and the `Rel` value of the offspring pair is `~0.5` such that it would typically be called as a `PO` pair we can deduce that this offspring pair is actually `FS`. Hereafter this is referred to as the "bowtie" pattern. Note that if either parent in the bowtie is missing no such deduction is possible and the direct `PO` relationship based on `Rel~=0.5` would be assumed. The red arrows in the graph below should not exist given we know both offspring share both parents. 

![bowtie txt](https://user-images.githubusercontent.com/5414719/70661988-fe5e0480-1c2a-11ea-8a83-da80bca41139.png)

Image produced from: [bowtie.txt](https://github.com/rhagenson/relped/files/3952658/bowtie.txt)

It is a known problem that we cannot differentiate between `Rel~=0.5` which is truly a `PO` relationship and `Rel~=0.5` which is truly a `HS` relationship. This problem was the original motivation for switching to a single relatedness input that can accommodate called relationships (see #18) such that the user can resolve these miscalled `PO`/direct relationships. Removing the relatedness entry of `O1,O2,~0.5` entirely is another potential solution as this will cause the offspring pair to be treated as `U` (Unrelated).

**Comment by rhagenson** [comment]
The fix for this should be introduced into the pruning stage (requiring a rename of `PruneToShortest(...)` as that will no longer be the case).
